// Languages from the "Admired and Desired" section of the Stack Overflow Developer Survey 2023
// https://survey.stackoverflow.co/2023/

pub const LANGUAGES: [&str; 51] = [
    "JavaScript",
    "Python",
    "TypeScript",
    "HTML/CSS",
    "SQL",
    "Rust",
    "C#",
    "Bash/Shell",
    "Go",
    "Java",
    "C++",
    "Kotlin",
    "C",
    "PHP",
    "PowerShell",
    "Dart",
    "Swift",
    "Ruby",
    "Lua",
    "Elixir",
    "Assembly",
    "Zig",
    "Haskell",
    "R",
    "Scala",
    "Julia",
    "F#",
    "Delphi",
    "Clojure",
    "Lisp",
    "Solidity",
    "GDScript",
    "Erlang",
    "Visual Basic (.Net)",
    "Groovy",
    "MATLAB",
    "Perl",
    "OCaml",
    "Objective-C",
    "VBA",
    "Nim",
    "Ada",
    "Crystal",
    "Prolog",
    "Fortran",
    "Apex",
    "APL",
    "Cobol",
    "SAS",
    "Raku",
    "Flow",
];
